on:
  push:
    branches:
      - main
jobs:
  scan-simples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Simple Scan
        uses: aquasecurity/trivy-action@master
        with:
          format: "table"
          severity: "CRITICAL,HIGH,MEDIUM"
          ignore-unfixed: true
          scan-type: "fs"
          scan-ref: "."
